server:
  port: 8181

spring:
  profiles:
    active: dev

geocoding:
  yandex_api_base_url: https://geocode-maps.yandex.ru/1.x
  apikey: ${API-KEY}
  results: 1
  format: json
  kind: street
  lang: ru_RU


